# Generated by Django 4.1.2 on 2022-11-01 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='name',
        ),
    ]
