# Generated by Django 4.1.2 on 2022-11-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tags',
        ),
    ]
