# Generated by Django 4.1.2 on 2022-11-02 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_group_identification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.profile'),
        ),
    ]
