# Generated by Django 4.1.2 on 2022-11-04 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_identification_aadhar_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
