# Generated by Django 4.1.2 on 2022-11-08 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_identification_tags_delete_tag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='Groups',
        ),
    ]
